# © 2025 Thor Thor
# Contact: codethor@gmail.com
# LinkedIn: https://www.linkedin.com/in/thor-thor0
# SPDX-License-Identifier: MIT

name: Bug report
description: Report a bug in DiliVet
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Steps to reproduce, expected vs actual
    validations: { required: true }
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `dilivet -version`
