# © 2025 Thor Thor
# Contact: codethor@gmail.com
# LinkedIn: https://www.linkedin.com/in/thor-thor0
# SPDX-License-Identifier: MIT

name: Feature request
description: Suggest an idea for DiliVet
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should DiliVet do?
