name: Feature request
description: Suggest an idea for DiliVet
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should DiliVet do?
